Update README.md
zelytra/BetterFleet pull request #15
Opened 2024-02-28 19:15 UTC by ZeTro-dev

Update of the README with the project presentation

2024-02-28 19:18 UTC, zelytra requested changes

2024-02-28 19:18 UTC, zelytra commented on README.md
> +![image](https://github.com/zelytra/BetterFleet/assets/84403666/3c218133-65ef-42af-ae68-dc6e7d4dd225)
Not absoluth/link path only relative path, and no random name
```suggestion
![image](/frontend/src/assets/file-name.png)
```

2024-02-28 20:30 UTC, dadodasyra commented
Do not merge, we first need to add a section about the WIP and todo's

2024-03-02 23:23 UTC, ZeTro-dev reviewed
Ok

2024-03-03 14:43 UTC, closed without merging