Server & game status detection
zelytra/BetterFleet pull request #21
Opened 2024-03-02 23:52 UTC by dadodasyra

It may still need modification in the main.rs to support javascript bridging with tauri.
I tried but it's a mess and don't have time for it.

The whole API behind is working, tried by running rust without tauri.

It needs Administrator priveleges

2024-03-03 20:47 UTC, dadodasyra commented
```ts
import { invoke } from '@tauri-apps/api/tauri'

setInterval(() => {
    invoke('get_game_status')
        .then((res) => {
                console.log(res);
                if (res === "InGame") {
                    invoke('get_server_ip')
                        .then((res) =>
                            console.log(res)
                        )
                }
        }).catch((e) => console.error(e))
}, 5000)

```
Get data example

2024-03-03 20:49 UTC, zelytra requested changes

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/api.rs
> +// Assuming these are your global variables in the `api` module
Message GPT

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/api.rs
> +pub enum GameStatus {
Ajouter des descriptif de chaque etat

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/api.rs
> +    pub async fn get_server_port(&self) -> u16 {
Ajouter doc

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/api.rs
> +    pub async fn get_last_updated_server_ip(&self) -> Instant {
Ajouter doc

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +            //println!("PID: {:?}", pid);
Debug à retirer

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +                //println!("UDP connections: {:?}", udp_connections);
Debug à retirer

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +                    println!("IP addresses: {:?}", ip_addresses);
Debug à retirer

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +                                    // This should never happen since when the player is not connected to a server, the game_status is MainMenu
Mauvais endroit du commentaire

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +                GameStatus::Closed => 5000,
Voir si possibilité de descendre sous la secondes voir les 500ms

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +fn get_local_hostname() -> std::io::Result<String> {
A documenter

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +pub fn find_pid_of(process_name: &str) -> Vec<String> {
A documenter

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +                        //println!("{:?}", recv_result);
Debug a retirer

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +        tokio::select! {
A documenter

2024-03-03 20:49 UTC, zelytra commented on frontend/src-tauri/src/fetch_informations.rs
> +                                //println!("{:?}", packet.transport);
Debug a retirer

2024-03-04 12:45 UTC, dadodasyra commented
I changed refresh to 500ms for MainMenu, without using powershell It should be acceptable..
Maybe in the future we may add a user settings to configure that..

2024-03-04 13:14 UTC, zelytra approved these changes

2024-03-04 13:15 UTC, merged